### ISSUE TITLE
Zone builder without ipv6 config

### ISSUE THREAD

**Issue by KlimasTech** [britannic/EdgeMax#1]
What lines in code i should delete or # to generating config without ipv6 rulles, zones, etc...

**Comment by britannic** [comment]
Comment any line that only contains a '[6]' near the end or remove the '6' from a line that has it. The number '6' instructs the parser to create an IPv6 rule. 

E.g. This line:
`(('adm', 'loc'), all_zones, ('description "Allow all connections"', 'action accept', 'state new enable', 'state established enable', 'state related enable'), [4, 6]),`

Will need to be rewritten as:
`(('adm', 'loc'), all_zones, ('description "Allow all connections"', 'action accept', 'state new enable', 'state established enable', 'state related enable'), [4]),`
