### ISSUE TITLE
Configure zones and packets direction

### ISSUE THREAD

**Issue by KlimasTech** [britannic/EdgeMax#2]
I have in this script set zones.
'WAN' eth0 DHCP
'LAN' eth1 172.16.1.0/24
'DMZ' eth2 10.10.1.0/24
'VPN' vti1 (openvpn site2site tunel)
'MGMT' vtun1 (remote access to  router) 192.168.1.0/30
'LOCAL' local-zone

I want allow all packets from LOCAL to ALL and from ALL to WAN. 

In zone DMZ i want all my serwers and access from LAN to defined ip and ports. 

From VPN only access to defined ip in DMZ.

From MGMT acces to LOCAL router and DMZ and VPN.

How i must edit this script ?

**Comment by britannic** [comment]
Please post your question on the [Edgemax forum](https://community.ubnt.com/t5/EdgeMAX/bd-p/EdgeMAX), as this is a configuration question and not an issue with the script itself. Another advantage, is you can tap into a much larger community of experts than here.
