### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by ghost** [britannic/EdgeMax#4]
bash install_dnsmasq_blklist.v3.6.2
1
error: Edgemax v1.9.7+hotfix is not supported, upgrade!

**Comment by britannic** [comment]
Had some issues with the repo, have moved it to: https://github.com/britannic/Adblock. Tested with v1.9.7+hotfix.4. Also, visit the thread at: https://community.ubnt.com/t5/EdgeMAX/CLI-Integrated-dnsmasq-Adblocking-amp-Blacklisting-v3-6-3-3-Easy/td-p/1344740
