### ISSUE TITLE
How can I "execute" the output from this script?

### ISSUE THREAD

**Issue by BrianG61UK** [britannic/EdgeMax#6]
The output from the script is obvviously inteneded to be "executed" on the Edge Router somehow.
How does one do that? (Other than using -U)

**Comment by britannic** [comment]
There are many scripts and utilities in this repo. In most cases you will need to find the script you're interested and follow the installation instructions. You'll also need to use scp or set up ftp on your router to transfer the files, or copy and paste content into a file on the router using an ssh session.

From the Repo README: Usage: Check the script's comments or run the script with "-h" to see how to use them.

**Comment by BrianG61UK** [comment]
Thank you for your response.
Sorry I should have been clearer.
I am referring to the output from the ubnt_fw_zone_gen.py script.
What is the recommended way of getting this in to the router?
I know I can use ubnt_fw_zone_gen.py -U but I want to edit it a bit first adding some extra delete commands to switch off my existing firewall.

**Comment by britannic** [comment]
Use scp to transfer your edited file or cut and paste via ssh. Then you'd run configure and source the file into the config session, then execute commit. Once you're happy with the result, save the config or use the load command to reload the previous configuration. Recommend you post any questions about the router configuration at [UBNT Community](https://community.ui.com/tags/edgemax).

**Comment by BrianG61UK** [comment]
But configure <outputfile doesn't work even if I add commit or save or sanything else I can think of to the end of the file.

Like everything EdgeMax it's totally and utterly unfathomable and notbody will give straight answers.

How the hell do Ubiquiti sell any of these?

**Comment by britannic** [comment]
You can't use console redirection inside the configure interpreter, you need to use "source" or its equivalent "." shorthand. Recommend you ask your questions over at [UBNT Community](https://community.ui.com/tags/edgemax).
